name: DynamicSurvival
main: com.nonkungch.dynamicsurvival.DynamicSurvival
version: 1.1
api-version: 1.21
author: NonKungCh
commands:
  ds:
    description: Dynamic Survival main command
    usage: /ds <setseason|setthirst|settemp|info|reload>
    permission: dynamicsurvival.admin
permissions:
  dynamicsurvival.admin:
    description: Allows admin commands
    default: op
