name: DynamicSurvival
main: com.nonkungch.dynamicsurvival.DynamicSurvival
version: 1.0
api-version: 1.21
author: NonKungCh
description: A plugin that adds dynamic seasons, temperature, and thirst mechanics to your survival world.
commands:
  ds:
    description: Dynamic Survival Base Command
    usage: /ds <reload|calendar>
    aliases: [dynamicsurvival]
permissions:
  ds.calendar:
    description: Open menu calendar /ds calendar
  ds.admin:
    description: Allows access to administrative commands like /ds reload
    default: op
    