# ต้องแน่ใจว่าชื่อคลาสหลักถูกต้อง
main: com.nonkungch.dynamicsurvival.DynamicSurvival
name: DynamicSurvival
version: 1.0-SNAPSHOT
author: NonKungCh
api-version: 1.21 # สำคัญมากสำหรับ 1.21+

commands:
  ds:
    description: Dynamic Survival Base Command
    usage: /ds <temp|thirst>
    permission: dynamicsurvival.admin
